queue: Hosted VS2017
variables: 
  BuildConfiguration: Release

steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- script: nbgv cloud
  displayName: Set Version
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'
    configuration: $(BuildConfiguration)
    packDirectory: $(Build.ArtifactStagingDirectory)\Artifacts    
    verbosityPack: Minimal
  displayName: Pack

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -s $(System.DefaultWorkingDirectory)\CodeCoverage.runsettings
  displayName: Run Tests
    
- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Artifacts
    artifactType: container
    artifactName: Artifacts
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))